vpc_name = "demovpc"
subnet1_name= "public_subnet"
subnet2_name= "private_subnet"
IG_name = "demovpc_IG"
RT1_name = "public_RT"
RT2_name = "private_RT"
nat_gateway_name = "nat_gateway"
instance_name1 = "bastion host"
